language: node_js
node_js:
  - stable
sudo: required
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install: 
  - yarn install --silent
script:
  - node scripts/dockerScripts build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  skip_cleanup: true
  script: node scripts/dockerScripts tag && node scripts/dockerScripts publish
  on:
    all_branches: true
env:
  global:
    - secure: Q6IAG8Ye/r4D+XYN0pRfYqrpSYoSvxQ8I3v4BARjV+GsQBuovFeR8a0Xkfl1pPi3IIwdn0em+rmmKICq0PpS0PCMBQlUUOirGDuU+NS0n+QEzcWH3Q8uNpIXAi5Z5piSg2Vm+641PcPRIcCCdklRiQvBunHm1kqrber74dFtXcsJo9mE+4eRJKbK6TQWfa6WyJo0WnxqOYobmJNvWoEccs83YorYaOi/aq7g1EQ6u1QRRy0q4f8qpGY6lPSBZVbqzMUqUwupHmToM6W2XRG6N7MyAiJF/+hO2IJ+VBqT+H5eZouUd0D67L4e7oug50czWv6Ai+Ai535QrVHYrEonea6qMWfyAWStZtbRHFr2VZHdFZLlcKndDqxr1NjbGpV+A/h4Lrcr+CLbWzRyg1ysOZuNSM8LckoW0xkfyJXGkHuZChzgfv+vy+CkAwajOavSIXRS4F577wbDqUFyDJl+Z6cArN/In8CtuRh0YFCd246ZwTfOAxKg7UMTBwhnTjmzlMss26wlAQSsLly5FQvry+Sx+AdJC40ja1DhwTg3vA22u+lfwA/3DNPQzGRXkcXPam3OvTd6N+YhodgBVubaHAxv0Fz3wvbSLJng2BErDOC/Wh5khfbHu69YUuv+JX+px0+oJbmRNBx0yrzQuTEuPhe/yAfPcOHBQGXlj65yvPY=
notifications:
  slack:
    secure: GPPkJOmpHU5A1vUEGFhDBI3iLtj4Xm7Zf6ztLxqJXsisO0LAlMfey3+A5pkdqnByj1uXTyNukAz2sH4cBkxKVpCQmPdEGpQE4gde+vC2uurPn4hvMJYZ3OcI/v2JTcq7oafdHZ3Nax5VozG2EDvgKKsuF7U10mZXKYj3Ew0UN4jRZiMZfQQKTZ8gQwqMRzRbRa8x/5krbMNiXsQGCANq/2Ylp7Hl0otUKs5lArQflukxXmmeUtW771yQOTFOq0oKecLxp/cPujewNtX62tcaUSzZ/zPS9P2CGwLYnNyWcVQ3RYP5vC4WTmrHb6yGwRFocIgIFVUCKH2P670FbAzwysrCFF/un2r+HaPwkg2fs9jlYCF3QoJjWzmkIVMwE0l9ezAZBytcAKlkK0AcY8+08eiC/te6viyQ4wrpq02MdsESU6l8CVSzQncFUv2qTWeb+MysL6U02SY6neVcPrGo5u6eq+1Q9PnbeymhloJkDlPsCKJJ6CVtxFb+jpSmXI/9KIaaaqcV1CULRC7VUkKh0osTp8xpczDIbRtUx7eDnXHWnJXBtnXH5JY26jBt/mKf0ObLVuaqs4q+jITI2D/OakyZN9z3ALbkPp5aRdLxwYIKnvQ3unlybtf45shFl6bHah/BBNEVdvgc9EV5fXaz/JL9OZfGaW/DgLY5ePrHAaY=
