language: node_js
node_js: stable
sudo: required
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
  - export PATH="$HOME/.yarn/bin:$PATH"
script: travis_wait node scripts/dockerUtil.js build
before_deploy:
 - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  skip_cleanup: true
  script: node node scripts/dockerUtil.js deploy
  on:
    all_branches: true